/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Controladora;
import Modelo.Sedes;
import javax.swing.JOptionPane;

/**
 *
 * @author juancamilo
 */
public class ConsultEditSedes extends javax.swing.JFrame {
    Controladora control = new Controladora();
    boolean editing = false;
    /**
     * Creates new form ConsultEditSedes
     */
    public ConsultEditSedes(Sedes s) {
        initComponents();
        this.setResizable(false);
        
        this.inputIDSede.setText(s.getId());
        this.inputCity.setText(s.getCiudad());
        this.inputAddress.setText(s.getDireccion());
        this.comboState.addItem(s.getEstado());
        control.alterComboJefeInConsult(comboJefe, s.getJefe());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputIDSede = new javax.swing.JTextField();
        inputCity = new javax.swing.JTextField();
        inputAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboJefe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputIDSede.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        inputIDSede.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        inputIDSede.setFocusable(false);

        inputCity.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        inputCity.setFocusable(false);

        inputAddress.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        inputAddress.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("Consult / Edit");

        comboState.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        comboState.setFocusable(false);

        jLabel2.setText("ID sede: ");

        comboJefe.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        comboJefe.setFocusable(false);

        jLabel3.setText("Ciudad:");

        saveButton.setBackground(new java.awt.Color(204, 255, 204));
        saveButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Direccion:");

        editButton.setBackground(new java.awt.Color(255, 204, 204));
        editButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        editButton.setText("EDIT");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("State: ");

        jLabel7.setText("Jefe de Taller:");

        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputIDSede)
                            .addComponent(inputCity)
                            .addComponent(inputAddress)
                            .addComponent(comboState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboJefe, 0, 225, Short.MAX_VALUE))))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputIDSede, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputCity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboState, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(comboJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBtn))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        if(editing){
            String[] cadena = comboJefe.getItemAt(comboJefe.getSelectedIndex()).split(",");
            System.out.println("Cadena 0 "+cadena[0]);
            if(inputIDSede.getText().equals("") || inputCity.getText().equals("") || inputAddress.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Error, you have null elements");
            }else{
                try{
                    int identification = Integer.parseInt(inputIDSede.getText());
                    if(identification<0){
                        JOptionPane.showMessageDialog(null, "Datos incorrectos \nintentelo nuevamente1");
                    }else if(control.updateSede(inputIDSede.getText(), inputCity.getText(), inputAddress.getText(), comboState.getItemAt(comboState.getSelectedIndex()), cadena[0])){
                        JOptionPane.showMessageDialog(null, "Success updating user");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Datos incorrectos \nintentelo nuevamente2");
                    }
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "The ID must be an Integer");
                }
            }
        }else{
            editing = false;
            this.dispose();
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        editing = true;
        //LA CEDULA NO SE PUEDE MODIFICAR POR RAZONES OBVIAS...XD
        //this.inputID.setFocusable(true);
        this.inputCity.setFocusable(true);
        this.inputAddress.setFocusable(true);
        /*
        this.comboState.setFocusable(true);
        if(comboState.getItemAt(comboState.getSelectedIndex()).equals("T")){
            this.comboState.addItem("F");
        }else{
            this.comboState.addItem("T");
        }*/

        this.comboState.setFocusable(true);
        if(comboState.getItemAt(comboState.getSelectedIndex()).equals("t")){
            this.comboState.addItem("f");
        }else{
            this.comboState.addItem("t");
        }
        if(comboJefe.getItemAt(comboJefe.getSelectedIndex()) == null){
            control.alterComboSedesUpdating(comboJefe, "");
        }else{
            control.alterComboSedesUpdating(comboJefe, comboJefe.getItemAt(comboJefe.getSelectedIndex()));
        }
        
        this.comboJefe.setFocusable(true);

        this.getContentPane().setBackground(java.awt.Color.pink);
        //this.inputID.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_editButtonActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboJefe;
    private javax.swing.JComboBox<String> comboState;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputCity;
    private javax.swing.JTextField inputIDSede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
