/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Controladora;
import Modelo.Users;
import Modelo.Jefes;
import Modelo.Producto;
import Modelo.Vendedor;
import ModeloDAO.UsersDAO;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class vistaVendedor extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form Home
     */
    Controladora control = new Controladora();
    boolean editing = false;
    DefaultTableModel md;
    DefaultTableModel mdSede;
    String JefeActualParaEditarXD;
    String[] arregloJefeActualNPI;
    public static Vendedor elVendedor;
    public static String idusuario;
    private Producto coincidencia;
    ProductosDisponibles productos;
    
    public vistaVendedor(String userID) {
        initComponents();
        setColor(btnPerfil);
        ind_1.setOpaque(true);
        
        System.out.println("------------->");
        this.elVendedor = control.consultProfileVENDEDOR(userID);
        this.profileID.setText(elVendedor.getId());
        this.profileFName.setText(elVendedor.getFname());
        this.profileLName.setText(elVendedor.getLname());
        this.profileTel.setText(elVendedor.getTel());
        this.profileDir.setText(elVendedor.getDir());
        this.profileWP.setText(elVendedor.getPosition());
        this.profileSede.setText(elVendedor.getSede());
        this.profileidSede.setText(elVendedor.getIdsede());
        
        Image icon = new ImageIcon(getClass().getResource("/Recursos/xyzicon.png")).getImage();
        super.setIconImage(icon);
        this.addWindowListener(this);
        this.lblFecha.setText(fechaActual());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPopUp = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputFN = new javax.swing.JTextField();
        inputLN = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        inputTel = new javax.swing.JTextField();
        inputDir = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCotizacion = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnProductosDisponibles = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        parent = new javax.swing.JPanel();
        PerfilVendedor = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        profileFName = new javax.swing.JLabel();
        profileID = new javax.swing.JLabel();
        profileLName = new javax.swing.JLabel();
        profileTel = new javax.swing.JLabel();
        profileDir = new javax.swing.JLabel();
        profileWP = new javax.swing.JLabel();
        SignOut = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        profileSede = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        profileidSede = new javax.swing.JLabel();
        JpCotizacion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfIDUsuario = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfIDproducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCotizacion = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfproducto = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        JBagregarprodu = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBlimpiar = new javax.swing.JButton();
        ProductosDisponibles = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDispoVen = new javax.swing.JTable();
        btnVenta = new javax.swing.JButton();
        jtfIDUsuario1 = new javax.swing.JTextField();
        jtfNombre1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JTidVenta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        editPopUp.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel19.setText("Editar Usuario");

        jLabel21.setText("ID user: ");

        jLabel26.setText("Nombre:");

        jLabel27.setText("Apellido:");

        inputID.setBackground(new java.awt.Color(204, 255, 255));
        inputID.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        inputID.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        inputID.setFocusable(false);

        inputFN.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        inputLN.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        saveButton.setBackground(new java.awt.Color(204, 255, 204));
        saveButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveButton.setText("GUARDAR");
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        exitBtn.setText("SALIR");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel30.setText("Telefono:");

        jLabel31.setText("Direccion:");

        javax.swing.GroupLayout editPopUpLayout = new javax.swing.GroupLayout(editPopUp.getContentPane());
        editPopUp.getContentPane().setLayout(editPopUpLayout);
        editPopUpLayout.setHorizontalGroup(
            editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPopUpLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel21)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(editPopUpLayout.createSequentialGroup()
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPopUpLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel19))
                    .addGroup(editPopUpLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPopUpLayout.setVerticalGroup(
            editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(39, 39, 39)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(inputFN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(inputLN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(editPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(0, 0, 0));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPerfilMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Perfil");

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(0, 135, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, -1));

        btnCotizacion.setBackground(new java.awt.Color(0, 0, 0));
        btnCotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCotizacionMousePressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cotización");

        javax.swing.GroupLayout btnCotizacionLayout = new javax.swing.GroupLayout(btnCotizacion);
        btnCotizacion.setLayout(btnCotizacionLayout);
        btnCotizacionLayout.setHorizontalGroup(
            btnCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCotizacionLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(0, 98, Short.MAX_VALUE))
        );
        btnCotizacionLayout.setVerticalGroup(
            btnCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCotizacionLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btnCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, -1));

        btnProductosDisponibles.setBackground(new java.awt.Color(0, 0, 0));
        btnProductosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosDisponiblesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductosDisponiblesMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Disponibilidad/Ventas");

        javax.swing.GroupLayout btnProductosDisponiblesLayout = new javax.swing.GroupLayout(btnProductosDisponibles);
        btnProductosDisponibles.setLayout(btnProductosDisponiblesLayout);
        btnProductosDisponiblesLayout.setHorizontalGroup(
            btnProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosDisponiblesLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        btnProductosDisponiblesLayout.setVerticalGroup(
            btnProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosDisponiblesLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnProductosDisponiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btnProductosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 590));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Multiply_25px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(821, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 880, 50));

        parent.setBackground(new java.awt.Color(255, 255, 255));
        parent.setLayout(new java.awt.CardLayout());

        PerfilVendedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel14.setText("PERFIL VENDEDOR");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel4.setText("Apellido: ");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel5.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel6.setText("Cargo:");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel12.setText("Direccion:");

        profileFName.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileFName.setText("jLabel15");

        profileID.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileID.setText("jLabel15");

        profileLName.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileLName.setText("jLabel15");

        profileTel.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileTel.setText("jLabel15");

        profileDir.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileDir.setText("jLabel15");

        profileWP.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileWP.setText("jLabel15");

        SignOut.setBackground(new java.awt.Color(255, 0, 51));
        SignOut.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setText("SALIR");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel33.setText("Código Sede:");

        profileSede.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileSede.setText("jLabel15");

        jLabel34.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel34.setText("Sede");

        profileidSede.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        profileidSede.setText("jLabel15");

        javax.swing.GroupLayout PerfilVendedorLayout = new javax.swing.GroupLayout(PerfilVendedor);
        PerfilVendedor.setLayout(PerfilVendedorLayout);
        PerfilVendedorLayout.setHorizontalGroup(
            PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilVendedorLayout.createSequentialGroup()
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PerfilVendedorLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel3))
                    .addGroup(PerfilVendedorLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SignOut)
                            .addComponent(jLabel18)))
                    .addGroup(PerfilVendedorLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel14))
                    .addGroup(PerfilVendedorLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PerfilVendedorLayout.createSequentialGroup()
                                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel33))
                                .addGap(72, 72, 72)
                                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(profileWP)
                                    .addComponent(profileDir)
                                    .addComponent(profileTel)
                                    .addComponent(profileLName)
                                    .addComponent(profileFName)
                                    .addComponent(profileID)
                                    .addComponent(profileidSede)))
                            .addGroup(PerfilVendedorLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profileSede)))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        PerfilVendedorLayout.setVerticalGroup(
            PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(43, 43, 43)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(profileID))
                .addGap(14, 14, 14)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileFName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(profileLName))
                .addGap(18, 18, 18)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(profileTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(profileDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(profileWP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(profileidSede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PerfilVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(profileSede))
                .addGap(60, 60, 60)
                .addComponent(SignOut)
                .addGap(32, 32, 32))
        );

        parent.add(PerfilVendedor, "card6");

        JpCotizacion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Cotización");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ID Usuario ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nombre");

        jtfIDUsuario.setEditable(false);

        jtfNombre.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("ID/Nombre  Producto");

        jtfIDproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDproductoActionPerformed(evt);
            }
        });
        jtfIDproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIDproductoKeyReleased(evt);
            }
        });

        jTCotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Color", "Alto", "Largo", "Ancho", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTCotizacion);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Producto");

        jtfproducto.setEditable(false);

        jtfTotal.setEditable(false);

        JBagregarprodu.setText("Agregar");
        JBagregarprodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagregarproduActionPerformed(evt);
            }
        });

        JBeliminar.setText("Eliminar");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });
        JBeliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JBeliminarKeyPressed(evt);
            }
        });

        JBlimpiar.setText("Limpiar");
        JBlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBlimpiarMouseClicked(evt);
            }
        });
        JBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpCotizacionLayout = new javax.swing.GroupLayout(JpCotizacion);
        JpCotizacion.setLayout(JpCotizacionLayout);
        JpCotizacionLayout.setHorizontalGroup(
            JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(JpCotizacionLayout.createSequentialGroup()
                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpCotizacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JpCotizacionLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(91, 91, 91))
                                .addGroup(JpCotizacionLayout.createSequentialGroup()
                                    .addComponent(jtfIDUsuario)
                                    .addGap(25, 25, 25)))
                            .addGroup(JpCotizacionLayout.createSequentialGroup()
                                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfIDproducto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)))
                        .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpCotizacionLayout.createSequentialGroup()
                                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(jtfNombre)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGap(108, 557, Short.MAX_VALUE))
                            .addGroup(JpCotizacionLayout.createSequentialGroup()
                                .addComponent(jtfproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(JBagregarprodu)
                                .addGap(35, 35, 35)
                                .addComponent(JBeliminar)
                                .addGap(34, 34, 34)
                                .addComponent(JBlimpiar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpCotizacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap())
            .addGroup(JpCotizacionLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpCotizacionLayout.setVerticalGroup(
            JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfIDproducto)
                    .addComponent(JBagregarprodu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jtfproducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parent.add(JpCotizacion, "card3");

        ProductosDisponibles.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Disponibilidad/Ventas");

        jtDispoVen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Color", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtDispoVen);

        btnVenta.setText("Realizar Venta");

        jtfIDUsuario1.setEditable(false);

        jtfNombre1.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Nombre");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("ID Usuario ");

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Total");

        jtTotal.setEditable(false);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JTidVenta.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("ID Venta");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFecha.setText("jLabel24");

        javax.swing.GroupLayout ProductosDisponiblesLayout = new javax.swing.GroupLayout(ProductosDisponibles);
        ProductosDisponibles.setLayout(ProductosDisponiblesLayout);
        ProductosDisponiblesLayout.setHorizontalGroup(
            ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                        .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jtfIDUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                                        .addComponent(jtfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnProductos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))
                            .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel23)))
                        .addContainerGap(381, Short.MAX_VALUE))
                    .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                        .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(JTidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenta)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductosDisponiblesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(117, 117, 117)
                .addComponent(lblFecha)
                .addGap(131, 131, 131))
        );
        ProductosDisponiblesLayout.setVerticalGroup(
            ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblFecha))
                .addGap(92, 92, 92)
                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProductosDisponiblesLayout.createSequentialGroup()
                        .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProductosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        parent.add(ProductosDisponibles, "card4");

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 880, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMousePressed
        // TODO add your handling code here:
        setColor(btnPerfil);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btnCotizacion, btnProductosDisponibles}, new JPanel[]{ind_2, ind_3});
        parent.removeAll();
        parent.add(PerfilVendedor);
        parent.repaint();
        parent.revalidate();

    }//GEN-LAST:event_btnPerfilMousePressed
    
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

    }//GEN-LAST:event_saveButtonActionPerformed
    

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.editPopUp.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        login2 log = new login2();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignOutActionPerformed

    private void btnCotizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCotizacionMousePressed
        // TODO add your handling code here:
        setColor(btnCotizacion);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btnPerfil, btnProductosDisponibles}, new JPanel[]{ind_1, ind_3});
        parent.removeAll();
        parent.add(JpCotizacion);
        parent.repaint();
        parent.revalidate();
        Users usuario = control.consultProfile(idusuario);
        jtfIDUsuario.setText(usuario.getId());
        jtfNombre.setText(usuario.getFname() + " " + usuario.getLname());
        

    }//GEN-LAST:event_btnCotizacionMousePressed

    private void jtfIDproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIDproductoKeyReleased
        // TODO add your handling code here:

        coincidencia = control.consultProductCoincidencia(jtfIDproducto.getText());
        jtfproducto.setText(coincidencia.getNombre());
        

    }//GEN-LAST:event_jtfIDproductoKeyReleased

    private void JBagregarproduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagregarproduActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo;
        modelo = null;
        int cantidad = 0;
        String[] titulos = {"Código", "Nombre", "Color", "Alto", "Largo", "Ancho", "Precio", "Cantidad"};
        
        if (jtfproducto.getText().length() == 0 || jtfproducto.getText().equalsIgnoreCase("Sin resultados...")) {
            
            JOptionPane.showMessageDialog(null, "El producto no existe ");
            
        } else {
            try {
                cantidad = Integer.parseInt(JOptionPane.showInputDialog("Inserte la cantidad"));
            } catch (NumberFormatException number) {
                JOptionPane.showMessageDialog(null, "Digíte solo números ");
            }
            String[] registro = new String[8];
            if (cantidad > 0 || cantidad <= 1000) {
                
                if (jTCotizacion.getRowCount() == 0) {
                    
                    modelo = new DefaultTableModel(null, titulos);
                } else {
                    
                    modelo = (DefaultTableModel) jTCotizacion.getModel();
                }
            }
            
            try {
                
                registro[0] = coincidencia.getId();
                registro[1] = coincidencia.getNombre();
                registro[2] = coincidencia.getColor();
                registro[3] = Integer.toString(coincidencia.getAlto());
                registro[4] = Integer.toString(coincidencia.getLargo());
                registro[5] = Integer.toString(coincidencia.getAncho());
                registro[6] = Integer.toString(coincidencia.getPrecio());
                registro[7] = Integer.toString(cantidad);
                
                modelo.addRow(registro);
                jTCotizacion.setModel(modelo);
                
                for (int c = 0; c < jTCotizacion.getColumnCount(); c++) {
                    Class<?> col_class = jTCotizacion.getColumnClass(c);
                    jTCotizacion.setDefaultEditor(col_class, null); // remove editor
                }
                total();
                
            } catch (Exception e) {
                
            }
            
        }
    }//GEN-LAST:event_JBagregarproduActionPerformed

    private void JBlimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBlimpiarMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_JBlimpiarMouseClicked

    private void JBeliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JBeliminarKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_JBeliminarKeyPressed

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        jtfTotal.setText("");
        jtfIDproducto.setText("");
        jtfproducto.setText("");
    }//GEN-LAST:event_JBlimpiarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnProductosDisponiblesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosDisponiblesMousePressed
        // TODO add your handling code here:
        setColor(btnProductosDisponibles);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btnCotizacion, btnPerfil}, new JPanel[]{ind_1, ind_2});
        parent.removeAll();
        parent.add(ProductosDisponibles);
        parent.repaint();
        parent.revalidate();
        Users usuario = control.consultProfile(idusuario);
        jtfIDUsuario1.setText(usuario.getId());
        jtfNombre1.setText(usuario.getFname() + " " + usuario.getLname());

    }//GEN-LAST:event_btnProductosDisponiblesMousePressed

    private void btnProductosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosDisponiblesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosDisponiblesMouseClicked

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo;
        String sede = profileidSede.getText();
        modelo = control.mostrarActivos(sede);
        productos = new ProductosDisponibles();
        productos.jTproductosDis.setModel(modelo);
        productos.setVisible(true);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.LEFT);
        productos.jTproductosDis.getColumnModel().getColumn(1).setCellRenderer(tcr);
        

    }//GEN-LAST:event_btnProductosActionPerformed

    private void jtfIDproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDproductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        eliminarProductoVenta();
        

    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mostrarProductosDispo() {
        DefaultTableModel modelo;
        String sede = profileidSede.getText();
        modelo = control.mostrarActivos(sede);
        productos.jTproductosDis.setModel(modelo);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.LEFT);
        productos.jTproductosDis.getColumnModel().getColumn(1).setCellRenderer(tcr);
    }
    
    public void cargarTableSede() {
        mdSede.setRowCount(0); //Para limpiar la tabla
        ArrayList<String[]> lista = control.consultSedes();
        for (int i = 0; i < lista.size(); i++) {
            mdSede.addRow(lista.get(i));
        }
        
    }
    
    private void setColor(JPanel pane) {
        pane.setBackground(new Color(153, 0, 0));
    }
    
    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(0, 0, 0));
            
        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }
        
    }
    
    public void total() {
        int resultado = 0;
        for (int i = 0; i < jTCotizacion.getRowCount(); i++) {
            resultado = Integer.parseInt(jTCotizacion.getValueAt(i, 6).toString()) * Integer.parseInt(jTCotizacion.getValueAt(i, 7).toString()) + resultado;
            jtfTotal.setText(Integer.toString(resultado));
            
        }
        
    }
    
    public void limpiar() {
        DefaultTableModel tb = (DefaultTableModel) jTCotizacion.getModel();
        int a = jTCotizacion.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
        
    }
    
    public void eliminar() {
        
        try {
            DefaultTableModel modelo = (DefaultTableModel) jTCotizacion.getModel();
            int select = jTCotizacion.getSelectedRow();
            modelo.removeRow(select);
            if (jTCotizacion.getRowCount() == 0) {
                jtfTotal.setText("");
            } else {
                total();
            }
        } catch (ArrayIndexOutOfBoundsException array) {
            JOptionPane.showMessageDialog(null, " Seleccione un producto ");
        }
        
    }
    
    public void eliminarProductoVenta() {
        
        try {
            DefaultTableModel modelo = (DefaultTableModel) jtDispoVen.getModel();
            int select = jtDispoVen.getSelectedRow();
            String codigo = jtDispoVen.getValueAt(jtDispoVen.getSelectedRow(), 0).toString();
            String cantidad = jtDispoVen.getValueAt(jtDispoVen.getSelectedRow(), 3).toString();
            String sede = elVendedor.getIdsede();
            control.updateCantidadSuma(codigo, cantidad, sede);
            modelo.removeRow(select);
            
            if (jtDispoVen.getRowCount() == 0) {
                jtTotal.setText("");
            } else {
                totalProductoVenta();
            }
        } catch (ArrayIndexOutOfBoundsException array) {
            JOptionPane.showMessageDialog(null, " Seleccione un producto ");
        }
        
    }
    
    public void totalProductoVenta() {
        
        int tamanio = vistaVendedor.jtDispoVen.getRowCount();
        int resultado = 0;
        
        for (int i = 0; i < tamanio; i++) {
            
            resultado += Integer.parseInt(vistaVendedor.jtDispoVen.getValueAt(i, 4).toString()) * Integer.parseInt(vistaVendedor.jtDispoVen.getValueAt(i, 3).toString());
            
        }
        
        vistaVendedor.jtTotal.setText(Integer.toString(resultado));
        
    }
    
    public String fechaActual() {
        
        SimpleDateFormat formato = new SimpleDateFormat("YYYY-MM-dd");
        Date fecha = new Date();
        String fechaActual = formato.format(fecha);
        
        return fechaActual;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagregarprodu;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBlimpiar;
    private javax.swing.JTextField JTidVenta;
    private javax.swing.JPanel JpCotizacion;
    private javax.swing.JPanel PerfilVendedor;
    private javax.swing.JPanel ProductosDisponibles;
    private javax.swing.JButton SignOut;
    private javax.swing.JPanel btnCotizacion;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JButton btnProductos;
    private javax.swing.JPanel btnProductosDisponibles;
    private javax.swing.JButton btnVenta;
    private javax.swing.JFrame editPopUp;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JTextField inputDir;
    private javax.swing.JTextField inputFN;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputLN;
    private javax.swing.JTextField inputTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCotizacion;
    public static javax.swing.JTable jtDispoVen;
    public static javax.swing.JTextField jtTotal;
    private javax.swing.JTextField jtfIDUsuario;
    private javax.swing.JTextField jtfIDUsuario1;
    private javax.swing.JTextField jtfIDproducto;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombre1;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfproducto;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel parent;
    private javax.swing.JLabel profileDir;
    private javax.swing.JLabel profileFName;
    private javax.swing.JLabel profileID;
    private javax.swing.JLabel profileLName;
    private javax.swing.JLabel profileSede;
    private javax.swing.JLabel profileTel;
    private javax.swing.JLabel profileWP;
    private javax.swing.JLabel profileidSede;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel side_pane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }
    
    @Override
    public void windowClosing(WindowEvent e) {
    }
    
    @Override
    public void windowClosed(WindowEvent e) {
        
        try {
            
            if (jtDispoVen.getRowCount() > 0) {
                
                String sede = elVendedor.getIdsede();
                
                for (int i = 0; i <= jtDispoVen.getRowCount(); i++) {
                    
                    String codigo = jtDispoVen.getValueAt(i, 0).toString();
                    String cantidad = jtDispoVen.getValueAt(i, 3).toString();
                    control.updateCantidadSuma(codigo, cantidad, sede);
                    
                }
            }
        } catch (Exception ex) {
            
        }
    }
    
    @Override
    public void windowIconified(WindowEvent e) {
    }
    
    @Override
    public void windowDeiconified(WindowEvent e) {
    }
    
    @Override
    public void windowActivated(WindowEvent e) {
    }
    
    @Override
    public void windowDeactivated(WindowEvent e) {
    }
    
}
